regenerate image so it works properly and is compressed with xz

diff --git a/build b/build
--- a/build
+++ b/build
@@ -13,6 +13,7 @@ unset cleanup_dest_img
 unset cleanup_ovf
 unset cleanup_original_image
 unset cleanup_created_image
+unset cleanup_mf
 cleanup() {
     [ -n "$NOCLEANUP" -a "$1" != "force" ] && exit || true
     [ -z "$cleanup_mountpoint" ] || {
@@ -46,6 +47,10 @@ cleanup() {
     [ -z "$cleanup_created_image" ] || {
         sudo rm -f "$cleanup_created_image"
         unset cleanup_created_image
+    }
+    [ -z "$cleanup_mf" ] || {
+        sudo rm -f "$cleanup_mf"
+        unset cleanup_mf
     }
 }
 trap cleanup EXIT
@@ -133,11 +138,11 @@ sudo rm -f "$targetdir"/partition1/etc/resolv.conf
 sudo cp /etc/resolv.conf "$targetdir"/partition1/etc/resolv.conf
 
 #fool system into believing that shit exists
-cleanup_fake="$targetdir"/partition1/fake
+fakedir="$targetdir"/partition1/fake
+sudo mkdir -p "$fakedir"
 for a in initctl invoke-rc.d restart start stop start-stop-daemon service ; do
-    sudo mkdir -p "$cleanup_fake"
-    echo "#/bin/bash" | sudo tee "$cleanup_fake"/$a > /dev/null
-    sudo chmod +x "$cleanup_fake"/$a
+    echo "#/bin/bash" | sudo tee "$fakedir"/$a > /dev/null
+    sudo chmod +x "$fakedir"/$a
 done
 
 #fire ansible up
@@ -145,6 +150,9 @@ sudo ANSIBLE_NOCOWS=1 PATH=/fake:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:
 
 #restore networking in chroot
 sudo ln -sf ../run/resolvconf/etc/resolv.conf "$targetdir"/partition1/etc/resolv.conf
+
+#cleanup the fake stuff
+sudo rm -rf "$fakedir"
 
 #unmount the filesystem
 sudo umount "$cleanup_mountpoint"
@@ -166,9 +174,19 @@ pushd "$targetdir" > /dev/null
 cleanup_dest_img="$PWD"/dts-publishingstudio-13.10-amd64-disk1.img
 qemu-img convert -S 512 -O qcow2 ubuntu-13.10-server-cloudimg-amd64-disk1.raw dts-publishingstudio-13.10-amd64-disk1.img
 
+ovfsum=`sha256sum dts-publishingstudio-13.10-amd64.ovf | cut -d ' ' -f 3`
+imgsum=`sha256sum dts-publishingstudio-13.10-amd64-disk1.img | cut -d ' ' -f 3`
+
+#generate manifest for extra anti-tampering goodness
+cleanup_mf="$PWD"/dts-publishingstudio-13.10-amd64.mf
+cat > dts-publishingstudio-13.10-amd64.mf << EOF
+SHA256(dts-publishingstudio-13.10-amd64.ovf)= $ovfsum
+SHA256(dts-publishingstudio-13.10-amd64-disk1.img)= $imgsum
+EOF
+
 #tar it all up
-cleanup_bad_ova="$PWD"/dts-publishingstudio-13.10-amd64.ova
-tar cv dts-publishingstudio-13.10-amd64-disk1.img dts-publishingstudio-13.10-amd64.ovf | pigz -9 -c > dts-publishingstudio-13.10-amd64.ova
+cleanup_bad_ova="$PWD"/dts-publishingstudio-13.10-amd64.ova.xz
+tar cv dts-publishingstudio-13.10-amd64.ovf dts-publishingstudio-13.10-amd64.mf dts-publishingstudio-13.10-amd64-disk1.img | xz -F xz > dts-publishingstudio-13.10-amd64.ova.xz
 cleanup_bad_ova=
 
 cleanup_original_image="$targetdir"/ubuntu-13.10-server-cloudimg-amd64-disk1.img
